# Nama dari workflow ini yang akan muncul di tab 'Actions' GitHub Anda
name: Build and Push Docker Image

# Event yang akan memicu workflow ini berjalan
on:
  # Akan berjalan setiap kali ada 'push' ke branch 'main'
  push:
    branches:
      - main # Pastikan ini sesuai dengan nama branch utama Anda (defaultnya 'main')

  # Mengizinkan pemicu workflow secara manual dari UI GitHub
  workflow_dispatch:

# Definisi job yang akan dijalankan
jobs:
  # Nama job: 'build-and-push'
  build-and-push:
    # Runner yang akan digunakan untuk menjalankan job ini
    runs-on: ubuntu-latest # Menggunakan mesin virtual Ubuntu terbaru yang disediakan GitHub

    # Langkah-langkah (steps) yang akan dieksekusi dalam job ini
    steps:
      # Langkah 1: Checkout kode repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4 # Menggunakan GitHub Action resmi untuk mengambil kode Anda

      # Langkah 2: Menyiapkan Docker Buildx (untuk kemampuan build yang lebih baik)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Menggunakan GitHub Action resmi untuk Buildx

      # Langkah 3: Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Menggunakan GitHub Action resmi untuk login Docker
        with:
          # Menggunakan GitHub Secrets untuk nama pengguna dan token Docker Hub Anda
          # Pastikan Anda telah mengkonfigurasi DOCKERHUB_USERNAME dan DOCKERHUB_TOKEN di Settings > Secrets > Actions
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 4: Membangun dan mendorong (push) Docker image ke Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Menggunakan GitHub Action resmi untuk build & push
        with:
          context: . # Menentukan direktori konteks build ('.' berarti root repositori)
          push: true # Mengaktifkan aksi 'push' ke registry Docker Hub
          tags: |
            # Tag image dengan nama pengguna Docker Hub Anda, nama repositori GitHub Anda, dan 'latest'
            ${{ secrets.DOCKERHUB_USERNAME }}/uaspkplworkflow:latest
            # Opsional: Tag image dengan nama pengguna Docker Hub Anda, nama repositori GitHub Anda, dan SHA commit
            # Ini membantu melacak versi image dengan commit spesifik
            ${{ secrets.DOCKERHUB_USERNAME }}/uaspkplworkflow:${{ github.sha }}
          # file: ./Dockerfile # Jika Dockerfile tidak di root, tentukan jalurnya di sini.
                               # Karena Dockerfile Anda ada di root, ini tidak perlu eksplisit.
